# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wick < Formula
  desc "Fast, zero-config secret and PII redaction for any text stream"
  homepage "https://krypsis.io/wick"
  version "0.1.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krypsis-io/wick/releases/download/v0.1.0/wick_0.1.0_darwin_amd64.tar.gz"
      sha256 "124dee04d8fbce17b2c57c2c297be3d67a9feed610f778eed6a4be1a6dcb4ca7"

      define_method(:install) do
        bin.install "wick"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/krypsis-io/wick/releases/download/v0.1.0/wick_0.1.0_darwin_arm64.tar.gz"
      sha256 "b5a743d1123b1168409644f6916756144416999e70bb6697ffaa3bd17a6139d8"

      define_method(:install) do
        bin.install "wick"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/krypsis-io/wick/releases/download/v0.1.0/wick_0.1.0_linux_amd64.tar.gz"
      sha256 "bed1edc60ac3fa7acd293d8151368be81f49ab58750786caf9ccdbbd3a935ea1"
      define_method(:install) do
        bin.install "wick"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krypsis-io/wick/releases/download/v0.1.0/wick_0.1.0_linux_arm64.tar.gz"
      sha256 "baf8d0d654195dd37f2ef2827e10744d8c5140b8ab2cb56992f6ae02eb8dae7e"
      define_method(:install) do
        bin.install "wick"
      end
    end
  end

  test do
    system "#{bin}/wick", "version"
  end
end
