# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wick < Formula
  desc "Fast, zero-config secret and PII redaction for any text stream"
  homepage "https://krypsis.io/wick"
  version "0.3.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krypsis-io/wick/releases/download/v0.3.0/wick_0.3.0_darwin_amd64.tar.gz"
      sha256 "af472d5995dee6862e7e2af09c902ad9abedb65d0aeb2ed4a44e9979451e304f"

      define_method(:install) do
        bin.install "wick"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/krypsis-io/wick/releases/download/v0.3.0/wick_0.3.0_darwin_arm64.tar.gz"
      sha256 "1ad219cf9d2ac7e0f52ce2df92a121f3fdc667f02cec7a6ab09cbecc6807f600"

      define_method(:install) do
        bin.install "wick"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/krypsis-io/wick/releases/download/v0.3.0/wick_0.3.0_linux_amd64.tar.gz"
      sha256 "cc79100061a6bf00577da2fe0b17a6e091d4280756253a02a8c3c75fb4713ffe"
      define_method(:install) do
        bin.install "wick"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krypsis-io/wick/releases/download/v0.3.0/wick_0.3.0_linux_arm64.tar.gz"
      sha256 "e0d455c5e0e446948062b010b61e021e9f8ebf70feabbe8b391d03e1bce786e4"
      define_method(:install) do
        bin.install "wick"
      end
    end
  end

  test do
    system "#{bin}/wick", "version"
  end
end
